version: '3'
name: "inventory-manager-dev-container"
services:
  dev:
    container_name: inventory-manager-db
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./pg-data:/var/lib/postgresql/data